spring:
  application:
    name: spring-cloud-skipper-shell
  main:
    banner-mode: 'off'
logging:
  pattern:
    console:
  # file:
  #   name: skipper-shell.log
  # level:
  #   org:
  #     springframework:
  #       shell: debug
