spring:
  application:
    name: spring-cloud-dataflow-shell
  main:
    banner-mode: 'off'
logging:
  pattern:
    console:
  file:
    name: dataflow-shell.log
  level:
    org:
      springframework:
        shell: debug
